dependency-dir: src/

include_directories:
    - ChibiOS_ext/os/hal/include
    - ChibiOS_ext/os/hal/ports/STM32/STM32F4xx
        
depends:
    - cmp_mem_access
    - crc
    - parameter
    - chibios-syscalls
    - msgbus

source:
    - src/sensors/VL53L0X/VL53L0X.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api_calibration.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api_core.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api_ranging.c
    - src/sensors/VL53L0X/Api/core/src/vl53l0x_api_strings.c
    - src/sensors/VL53L0X/Api/platform/src/vl53l0x_i2c_platform.c
    - src/sensors/VL53L0X/Api/platform/src/vl53l0x_platform.c
    - src/config_flash_storage.c

target.arm:
    - ChibiOS_ext/os/hal/src/dcmi.c
    - ChibiOS_ext/os/hal/ports/STM32/STM32F4xx/dcmi_lld.c
    - src/audio/audio_thread.c    
    - src/sensors/battery_level.c
    - src/sensors/imu.c
    - src/sensors/mpu9250.c
    - src/sensors/proximity.c
    - src/cmd.c
    - src/exti.c
    - src/i2c_bus.c
    - src/ir_remote.c    
    - src/leds.c
    - src/main.c
    - src/memory_protection.c
    - src/motors.c
    - src/panic.c
    - src/usbcfg.c
    - src/utility.c    
    - src/camera/po8030.c
    - src/camera/dcmi_camera.c
    - src/flash/flash.c

templates:
    src/src.mk.jinja: src/src.mk
